/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './autosizeInput.component';
const styles_AutosizeComponent:any[] = ['[_nghost-%COMP%] { display:block;position: fixed; visibility:hidden; top: -9999px; left: 0px;}'];
export const RenderType_AutosizeComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_AutosizeComponent,data:{}});
export function View_AutosizeComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{shadowElement:0}),(_l()(),i0.ɵeld(1,0,[[1,
      0],['shadowElement',1]],(null as any),1,'span',[['style','white-space:pre;']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(2,(null as any),['','']))],(null as any),(_ck,_v) => {
    var _co:i1.AutosizeComponent = _v.component;
    const currVal_0:any = _co.autosizeValue;
    _ck(_v,2,0,currVal_0);
  });
}
export function View_AutosizeComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'div',[['autosize',
      '']],(null as any),(null as any),(null as any),View_AutosizeComponent_0,RenderType_AutosizeComponent)),
      i0.ɵdid(1,49152,(null as any),0,i1.AutosizeComponent,[i0.ElementRef],(null as any),
          (null as any))],(null as any),(null as any));
}
export const AutosizeComponentNgFactory:i0.ComponentFactory<i1.AutosizeComponent> = i0.ɵccf('div[autosize]',
    i1.AutosizeComponent,View_AutosizeComponent_Host_0,{autosizeValue:'autosizeValue'},
    {},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NpbW9uZXJhZGljZS9Qcm9qZWN0cy9uZ3gtaW5wdXQtYXV0b3NpemUvc3JjL2F1dG9zaXplSW5wdXQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3NpbW9uZXJhZGljZS9Qcm9qZWN0cy9uZ3gtaW5wdXQtYXV0b3NpemUvc3JjL2F1dG9zaXplSW5wdXQuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvc2ltb25lcmFkaWNlL1Byb2plY3RzL25neC1pbnB1dC1hdXRvc2l6ZS9zcmMvYXV0b3NpemVJbnB1dC5jb21wb25lbnQudHMuQXV0b3NpemVDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3NpbW9uZXJhZGljZS9Qcm9qZWN0cy9uZ3gtaW5wdXQtYXV0b3NpemUvc3JjL2F1dG9zaXplSW5wdXQuY29tcG9uZW50LnRzLkF1dG9zaXplQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHNwYW4gc3R5bGU9XCJ3aGl0ZS1zcGFjZTpwcmU7XCIgI3NoYWRvd0VsZW1lbnQ+e3thdXRvc2l6ZVZhbHVlfX08L3NwYW4+IiwiPGRpdiBhdXRvc2l6ZT48L2Rpdj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7OzsyRENBQTtNQUFBO01BQUEsd0VBQThDO2FBQUE7O0lBQUE7SUFBQTs7OztvQkNBOUM7TUFBQTthQUFBO1VBQUE7Ozs7In0=
