/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './autosizeInput.module';
import * as i2 from './autosizeInput.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/forms';
export const AutosizeInputModuleNgFactory:i0.NgModuleFactory<i1.AutosizeInputModule> = i0.ɵcmf(i1.AutosizeInputModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.AutosizeComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,
              i4.ɵi,i4.ɵi,([] as any[])),i0.ɵmpd(512,i3.CommonModule,i3.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i4.ɵba,i4.ɵba,([] as any[])),i0.ɵmpd(512,
              i4.FormsModule,i4.FormsModule,([] as any[])),i0.ɵmpd(512,i1.AutosizeInputModule,
              i1.AutosizeInputModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NpbW9uZXJhZGljZS9Qcm9qZWN0cy9uZ3gtaW5wdXQtYXV0b3NpemUvc3JjL2F1dG9zaXplSW5wdXQubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3NpbW9uZXJhZGljZS9Qcm9qZWN0cy9uZ3gtaW5wdXQtYXV0b3NpemUvc3JjL2F1dG9zaXplSW5wdXQubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
